# Generated by Django 3.2.5 on 2021-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
