# Generated by Django 3.2.5 on 2021-08-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_myuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
