# Generated by Django 3.2.5 on 2021-07-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
