# Generated by Django 3.2.5 on 2021-07-17 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210716_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='information2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
