# Generated by Django 3.2.5 on 2021-07-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='image',
            field=models.ImageField(default=True, upload_to='product/color/'),
        ),
    ]
