# Generated by Django 3.2.5 on 2021-07-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
