# Generated by Django 3.2.5 on 2021-07-19 22:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
