# Generated by Django 3.2.5 on 2021-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='product/color/'),
        ),
    ]
