# Generated by Django 3.2.5 on 2021-08-02 03:12

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210802_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گاربر')),
                ('lastName', models.CharField(max_length=100, verbose_name='نام فامیلی کاربر')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل کاربر')),
                ('phone', models.PositiveIntegerField(max_length=100, verbose_name='شماره تماس کاربر')),
                ('message', models.CharField(max_length=1000, verbose_name='پیام کاربر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='create',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ساخت دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ نظر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریح ثیت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
    ]
