# Generated by Django 3.2.5 on 2021-08-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210802_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='شماره تماس کاربر'),
        ),
    ]
