# Generated by Django 3.2.5 on 2021-08-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید محصول'),
        ),
    ]
