# Generated by Django 3.2.5 on 2021-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='عکس محصول2 (اختیاری)'),
        ),
    ]
