# Generated by Django 3.2.5 on 2021-07-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
