# Generated by Django 3.2.5 on 2021-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_id_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.CharField(blank=True, choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شده', 'ارسال شده')], max_length=30),
        ),
    ]
