# Generated by Django 3.2.5 on 2021-08-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210801_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شده', 'ارسال شده')], default='در حال پردازش', max_length=30),
        ),
    ]
