# Generated by Django 3.2.5 on 2021-08-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(choices=[('a', 'پرداخت نشده'), ('b', 'بیانه پرداخت شده'), ('c', 'کامل پرداخت شده')], default='a', max_length=30),
        ),
    ]
