# Generated by Django 3.2.5 on 2021-08-02 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210802_0058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0013_auto_20210802_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام کد'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=models.DateTimeField(verbose_name='تاریخ پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=models.DateTimeField(verbose_name='تاریخ شروع تخفیف'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order.order', verbose_name='سبد سفارش'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='quantity',
            field=models.IntegerField(verbose_name='تعداد سفارش'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.variants', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='نظر کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='f_name',
            field=models.CharField(max_length=300, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='l_name',
            field=models.CharField(max_length=300, verbose_name='نام فامیلی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('a', 'پرداخت نشده'), ('b', 'بیانه پرداخت شده'), ('c', 'کامل پرداخت شده')], default='a', max_length=30, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شده', 'ارسال شده')], default='در حال پردازش', max_length=30, verbose_name='وضعیت ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
