# Generated by Django 3.2.5 on 2021-08-02 01:05

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210802_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع تخفیف'),
        ),
    ]
