# Generated by Django 3.2.5 on 2021-08-02 03:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210802_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثیت سفارش'),
        ),
    ]
