# Generated by Django 3.2.5 on 2021-08-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='radio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نحوه پرداخت'),
        ),
    ]
