# Generated by Django 3.2.5 on 2021-08-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_radio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='radio',
            new_name='radio2',
        ),
    ]
